#!/bin/sh

ver="$(grep -m1 engrampa configure.ac | cut -f 3 -d '[' | cut -f 1 -d ']')"

dir=engrampa-${ver}

mkdir -p ../$dir

cp -rf $PWD/* ../$dir

(
	cd ../$dir
	./autogen.sh
	rm -rf autom4te.cache
	rm -rf .tx
	rm -rf caja
	rm -f zrelease
)

cd ..

tar -Jcf ${dir}.tar.xz $dir

### END ###